version: "3.8"
services:
  main:
    env_file: .env.dev
    image: gcr.io/seanhwangg/worship_ppt
    build:
      context: .
      target: image-dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./worship_ppt:/worship_ppt
