# [ref] https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows
name: hosting

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      # The type of runner that the job will run on
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose build
          docker-compose run main python -m worship_ppt.test

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: seanhwangg
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Authorize Docker push
        run: |
          gcloud auth configure-docker
          docker-compose push

      - name: Deploy
        run: |
          gcloud run deploy worship-ppt --image gcr.io/seanhwangg/worship_ppt \
            --region us-central1 --platform "managed" \
            --service-account firebase-adminsdk-h70pe@seanhwangg.iam.gserviceaccount.com
